spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  application:
    name: settlement-system

app:
  base-url: https://t2.mobidic.shop
  timezone: Asia/Seoul

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: ${JWT_EXPIRATION_SECONDS}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    com.deepflow.settlementsystem: DEBUG

kakao:
  rest-api-key: ${REST_API_KEY}
  redirect-url: ${REDIRECT_URI}
  client-secret: ${CLIENT_SECRET}