spring:
  application:
    name: settlement-system

  datasource: # 테스트 DB
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

naver:
  ocr:
    url:
    secret:

logging:
  level:
    root: INFO
    com.deepflow.settlementsystem: INFO

